const express=require('express')
const app=express()
const cors=require('cors')
// app.use(authUser)
app.use(cors())
const userRouter=require('./routes/users')
const courseRouter=require('./routes/courses')
const studentRouter=require("./routes/students")
const videoRouter=require('./routes/videos')
const adminRouter=require('./routes/admin')
const jwt = require("jsonwebtoken")
const config=require('./utils/config')
const authUser=require('./utils/auth')
app.use(express.json())
// app.use(authUser)

app.use('/user',userRouter)
app.use('/courses',courseRouter)
app.use('/students',studentRouter)
app.use('/videos',videoRouter)
app.use('/admin',adminRouter)
app.listen(4000,'localhost',(req,res)=>{
    console.log("Server is listening at port 4000");
})

